PETOSS 517 | Python vulnerabilities
XeroAPI/xero-python pull request #158
Opened 2024-10-08 06:13 UTC by sangeet-joy-tw

2024-10-08 10:21 UTC, vigneshk-tw requested changes

2024-10-08 10:21 UTC, vigneshk-tw commented on .github/workflows/build-test-lint.yml
> +               pip-audit -r requirements.txt
can we combine and try like this?
`pip-audit -r requirements.txt -r requirements/dev.txt`

2024-10-08 11:43 UTC, vigneshk-tw approved these changes

2024-10-11 06:41 UTC, manishT72 approved these changes

2024-10-11 07:11 UTC, merged